"""Contrôle par mutations : casse volontairement chaque règle et vérifie qu'un test échoue.

Usage : python scripts/mutations.py lot01
Chaque lot ajoute sa liste de mutations ci-dessous. Une mutation qui laisse tous les tests
verts signale un test manquant : le lot n'est pas livré tant qu'elle « survit ».
"""
import pathlib
import subprocess
import sys

RACINE = pathlib.Path(__file__).resolve().parent.parent

MUTATIONS = {
    "lot01": [
        ("app/core/sante.py", 'return {"statut": OK if tout_va_bien else INDISPONIBLE', 'return {"statut": OK'),
        ("app/core/sante.py", "all(valeur == OK", "any(valeur == OK"),
        ("app/core/sante.py", "        return OK\n    except Exception:\n        return INDISPONIBLE\n\n\ndef verifier_redis", "        return OK\n    except Exception:\n        return OK\n\n\ndef verifier_redis"),
        ("app/core/sante.py", "        client.ping()\n        return OK\n    except Exception:\n        return INDISPONIBLE", "        client.ping()\n        return OK\n    except Exception:\n        return OK"),
        ("app/main.py", "code = 200 if etat", "code = 200 or etat"),
        ("app/core/config.py", 'return self.environnement != "production"', "return True"),
        ("app/entreprises/niu.py", "if not niu:", "if False:"),
        ("app/entreprises/niu.py", "if len(niu) > LONGUEUR_MAX:", "if len(niu) > LONGUEUR_MAX + 1:"),
        ("app/entreprises/niu.py", ".upper()", ""),
        ("app/entreprises/niu.py", r're.sub(r"[\s\-]", "", valeur)', r're.sub(r"[\s]", "", valeur)'),
        ("app/entreprises/niu.py", "if not niu.isalnum():", "if False:"),
        ("app/entreprises/niu.py", "if valeur is None:", "if False:"),
        ("migrations/versions/0001_socle.py", '"active": True', '"active": False'),
        ("migrations/versions/0001_socle.py", 'sa.UniqueConstraint("juridiction_code", "niu", name="uq_entreprises_juridiction_niu"),', ""),
        ("migrations/versions/0001_socle.py", 'sa.UniqueConstraint("juridiction_code", "niu"', 'sa.UniqueConstraint("niu"'),
        ("migrations/versions/0001_socle.py", 'sa.ForeignKey("juridictions.code"), nullable=False', "nullable=False"),
    ],
    "lot02": [
        ("app/conversation/moteur.py", "return len(texte) > LONGUEUR_MAX", "return len(texte) > LONGUEUR_MAX + 1"),
        ("app/conversation/moteur.py", "if premier_mot in SALUTATIONS:", "if mots in SALUTATIONS:"),
        ("app/conversation/moteur.py", "if mots == valeur:", "if valeur in mots:"),
        ("app/conversation/normalisation.py", 'encode("ascii", "ignore")', 'encode("utf-8", "ignore")'),
        ("app/conversation/normalisation.py", ".lower()", ""),
        ("app/conversation/moteur.py", "if texte is None or not texte.strip():", "if texte is None:"),
        ("app/conversation/moteur.py", "texte=texte[:LONGUEUR_MAX]", "texte=texte"),
        ("app/conversation/moteur.py", "            Conversation.canal == canal, Conversation.identifiant_externe == identifiant\n        )", "            Conversation.identifiant_externe == identifiant\n        )"),
        ("app/conversation/moteur.py", ".where(Conversation.canal == canal, Conversation.identifiant_externe == identifiant)\n            .order_by", ".where(Conversation.canal == canal)\n            .order_by"),
        ("app/conversation/moteur.py", ".order_by(Message.id)", ".order_by(Message.id.desc())"),
        ("app/conversation/moteur.py", "return Reponse(mf.ACCUEIL, list(mf.MENU))", "return Reponse(mf.ACCUEIL)"),
        ("app/conversation/messages_fixes.py", "Tapez « menu » pour voir ce que je peux faire pour vous.", "Tape « menu » pour voir ce que je peux faire pour toi."),
        ("app/canaux/web.py", "if not get_settings().essai_actif:", "if False:"),
        ("app/canaux/web.py", "jeton = jeton_valide(request) or secrets.token_urlsafe(32)", "jeton = secrets.token_urlsafe(32)"),
        ("app/canaux/web.py", "if jeton and 20 <= len(jeton)", "if jeton and 0 <= len(jeton)"),
        ("app/canaux/web.py", 'jeton.replace("-", "").replace("_", "").isalnum()', "True"),
        ("app/canaux/web.py", "httponly=True", "httponly=False"),
        ("app/canaux/web.py", 'samesite="strict"', 'samesite="lax"'),
        ("app/canaux/web.py", "    if jeton is None:\n        raise HTTPException(status_code=401", "    if False:\n        raise HTTPException(status_code=401"),
        ("app/canaux/web.py", "raise HTTPException(status_code=422", "raise HTTPException(status_code=400"),
        ("app/static/js/essai.js", "bulle.textContent = texte;", "bulle.innerHTML = texte;"),
        ("docker-compose.yml", "${JEFF_PORT:-8020}", "${JEFF_PORT:-8010}"),
        # Mutation de l'import de app.models retirée au lot 4 : tous les modèles sont désormais
        # chargés par le chemin normal (app.main → canaux → conversation → regles), elle était équivalente.
        ("migrations/versions/0002_conversations.py", 'sa.UniqueConstraint("canal", "identifiant_externe", name="uq_conversations_canal_identifiant"),', ""),
    ],
    "lot03": [
        ("app/conversation/montants.py", 'brut = re.sub(UNITES_MONETAIRES, " ", brut)', "brut = brut"),
        ("app/conversation/montants.py", 'brut = re.sub(r"\\bde\\b", " ", brut).strip()', "brut = brut.strip()"),
        ("app/conversation/montants.py", "if unite not in MULTIPLICATEURS:", "if False:"),
        ("app/conversation/montants.py", "if valeur != valeur.to_integral_value():", "if False:"),
        ("app/conversation/montants.py", 'chiffres.replace(",", ".")', "chiffres"),
        ("app/conversation/montants.py", r're.fullmatch(r"\d{1,3}(\.\d{3})+", chiffres)', r're.fullmatch(r"[\d.]+", chiffres)'),
        ("app/conversation/montants.py", "if montant > MONTANT_MAX:", "if montant > MONTANT_MAX * 10:"),
        ("app/conversation/montants.py", '"million": 10**6, "millions": 10**6, "m": 10**6', '"million": 10**6, "millions": 10**3, "m": 10**6'),
        ("app/conversation/montants.py", "if normaliser(texte) in MOTS_ZERO:", "if False:"),
        ("app/conversation/montants.py", "chiffres = re.sub(ESPACES, \"\", texte)", "chiffres = re.sub(ESPACES, \"\", normaliser(texte))"),
        ("app/conversation/montants.py", "if nombre > maximum:", "if nombre > maximum + 1:"),
        ("app/conversation/montants.py", 'return f"{montant:,}".replace(",", ESPACE_INSECABLE)', 'return f"{montant:,}".replace(",", " ")'),
        ("app/conversation/onboarding.py", "if len(valeur) < minimum:", "if len(valeur) < minimum - 1:"),
        ("app/conversation/onboarding.py", "if len(valeur) > maximum:", "if len(valeur) > maximum + 1:"),
        ("app/conversation/onboarding.py", "    if niu_deja_connu(session, niu):\n        raise ReponseInvalide(mf.NIU_DEJA_CONNU)", "    if False:\n        raise ReponseInvalide(mf.NIU_DEJA_CONNU)"),
        ("app/conversation/onboarding.py", "Entreprise.juridiction_code == get_settings().juridiction, Entreprise.niu == niu", "Entreprise.niu == niu"),
        ("app/conversation/onboarding.py", "if mots in {str(numero), normaliser(libelle), *synonymes}:", "if mots in {str(numero), *synonymes}:"),
        ("app/conversation/onboarding.py", "if not numero.isalnum() or not 3 <= len(numero) <= 30:", "if not 3 <= len(numero) <= 30:"),
        ("app/conversation/onboarding.py", 'if mots in {"plus tard", "je ne sais pas", "je ne l ai pas", "inconnu"}:', "if False:"),
        ("app/conversation/onboarding.py", 'condition=lambda donnees: (donnees.get("nombre_salaries") or 0) > 0,', "condition=lambda donnees: True,"),
        ("app/conversation/onboarding.py", "        if cle == \"nombre_salaries\" and cnps.condition(donnees) and cnps.cle not in donnees:", "        if False:"),
        ("app/conversation/onboarding.py", "    if donnees.get(RETOUR_RECAP):", "    if False:"),
        ("app/conversation/onboarding.py", '        donnees.pop("numero_employeur_cnps", None)', "        pass"),
        ("app/conversation/onboarding.py", "            parcours.statut = ABANDONNE\n            return Reponse(mf.PLUS_TARD", "            return Reponse(mf.PLUS_TARD"),
        ("app/conversation/onboarding.py", "if mots.isdigit() and 1 <= int(mots) <= len(proposees):", "if mots.isdigit() and 0 <= int(mots) <= len(proposees):"),
        ("app/conversation/onboarding.py", "    if niu_deja_connu(session, donnees[\"niu\"]):", "    if False:"),
        ("app/conversation/onboarding.py", '    valeurs["assujetti_tva_declare"] = None if tva == INCONNU else tva == "oui"', '    valeurs["assujetti_tva_declare"] = tva == "oui"'),
        ("app/conversation/onboarding.py", "    conversation.entreprise_id = entreprise.id\n", ""),
        ("app/conversation/onboarding.py", "    parcours.statut = TERMINE\n", ""),
        ("app/conversation/onboarding.py", "juridiction_code=get_settings().juridiction,", 'juridiction_code="CI",'),
        ("app/conversation/moteur.py", "            parcours.statut = EN_PAUSE\n", ""),
        ("app/conversation/moteur.py", "            parcours.statut = ABANDONNE\n            annule =", "            annule ="),
        ("app/conversation/moteur.py", 'if mots == "reprendre" or reprise_modification or (sans_profil and mots in CHOIX_AVEC_PROFIL):', 'if mots == "reprendre" or reprise_modification:'),
        ("app/conversation/moteur.py", "if sans_profil and mots in CHOIX_AVEC_PROFIL and parcours is None:", "if mots in CHOIX_AVEC_PROFIL and parcours is None:"),
        ("app/conversation/moteur.py", 'CHOIX_AVEC_PROFIL = {"1", "2", "3", "5"}', 'CHOIX_AVEC_PROFIL = {"1", "2", "3", "4", "5"}'),
        ("app/conversation/models.py", "postgresql_where=text(\"statut IN ('en_cours', 'en_pause')\"),", "postgresql_where=text(\"statut IN ('en_cours')\"),"),
        ("migrations/versions/0003_onboarding.py", "postgresql_where=sa.text(\"statut IN ('en_cours', 'en_pause')\"),", "postgresql_where=sa.text(\"statut IN ('en_cours')\"),"),
        ("migrations/versions/0003_onboarding.py", "        unique=True,\n", ""),
    ],
    "lot04": [
        ("app/regles/conditions.py", "        if NON in resultats:\n            return NON\n        return INCERTAIN if INCERTAIN in resultats else OUI", "        if NON in resultats:\n            return NON\n        return OUI"),
        ("app/regles/conditions.py", "        if NON in resultats:\n            return NON\n", "        if False:\n            return NON\n"),
        ("app/regles/conditions.py", "        if OUI in resultats:\n            return OUI\n", "        if False:\n            return OUI\n"),
        ("app/regles/conditions.py", "        return INCERTAIN if INCERTAIN in resultats else NON", "        return NON"),
        ("app/regles/conditions.py", "return {OUI: NON, NON: OUI}.get(resultat, INCERTAIN)", "return {OUI: NON, NON: OUI}.get(resultat, NON)"),
        ("app/regles/conditions.py", "    if valeur is None:\n        return INCERTAIN", "    if valeur is None:\n        return NON"),
        ("app/regles/conditions.py", "        return OUI if valeur is None else NON", "        return OUI"),
        ("app/regles/conditions.py", "        return NON if valeur is None else OUI", "        return OUI"),
        ("app/regles/conditions.py", '"superieur": lambda a, b: a > b,', '"superieur": lambda a, b: a >= b,'),
        ("app/regles/conditions.py", '"inferieur": lambda a, b: a < b,', '"inferieur": lambda a, b: a <= b,'),
        ("app/regles/conditions.py", '"superieur_ou_egal": lambda a, b: a >= b,', '"superieur_ou_egal": lambda a, b: a > b,'),
        ("app/regles/conditions.py", '"inferieur_ou_egal": lambda a, b: a <= b,', '"inferieur_ou_egal": lambda a, b: a < b,'),
        ("app/regles/conditions.py", '"different": lambda a, b: a != b,', '"different": lambda a, b: a == b,'),
        ("app/regles/conditions.py", "    if champ not in CHAMPS:", "    if False:"),
        ("app/regles/conditions.py", "    if op not in COMPARAISONS:", "    if False:"),
        ("app/regles/conditions.py", '    if op == "dans" and not isinstance(condition["valeur"], list):', "    if False:"),
        ("app/regles/conditions.py", '        if condition != {"toujours": True}:', "        if False:"),
        ("app/regles/conditions.py", "        if len(condition) != 1 or not isinstance(sous, list) or not sous:", "        if not isinstance(sous, list):"),
        ("app/regles/conditions.py", '    if set(condition) != {"champ", "op", "valeur"}:', "    if False:"),
        ("app/regles/conditions.py", "    except TypeError:", "    except KeyError:"),
        ("app/regles/chargement.py", '    if not isinstance(brute["code"], str) or not re.fullmatch(r"[A-Z0-9_]{3,60}", brute["code"]):', '    if not isinstance(brute["code"], str):'),
        ("app/regles/chargement.py", 'or isinstance(brute["version"], bool) or brute["version"] < 1:', 'or brute["version"] < 1:'),
        ("app/regles/chargement.py", '    if brute["type"] == "obligation" and periodicite is None:', "    if False:"),
        ("app/regles/chargement.py", "    if du and au and au < du:", "    if False:"),
        ("app/regles/chargement.py", "            if cle in vues:", "            if False:"),
        ("app/regles/chargement.py", "        if deja is not None and contenu(deja) != contenu(regle):", "        if False:"),
        ("app/regles/chargement.py", "    if erreurs:\n        raise ReglesInvalides(erreurs)\n\n    bilan", "    if False:\n        raise ReglesInvalides(erreurs)\n\n    bilan"),
        ("app/regles/chargement.py", "        elif deja.statut != regle[\"statut\"]:\n            deja.statut = regle[\"statut\"]", "        elif deja.statut != regle[\"statut\"]:\n            pass"),
        ("app/regles/chargement.py", 'CONTENU = (REQUIS | OPTIONNELS) - {"statut"}', "CONTENU = REQUIS | OPTIONNELS"),
        ("app/regles/chargement.py", "    if session.get(Juridiction, juridiction) is None:", "    if False:"),
        ("app/regles/charger.py", "        return 1", "        return 0"),
        ("app/regles/moteur.py", '"regime_declare": None if regime == INCONNU else regime,', '"regime_declare": regime,'),
        ("app/regles/moteur.py", "            Regle.statut.in_(STATUTS_VISIBLES),\n", ""),
        ("app/regles/moteur.py", "            Regle.applicable_du <= jour,\n", ""),
        ("app/regles/moteur.py", "or_(Regle.applicable_au.is_(None), Regle.applicable_au >= jour),", "or_(Regle.applicable_au.is_(None), Regle.applicable_au > jour),"),
        ("app/regles/moteur.py", "            Regle.juridiction_code == juridiction,\n", ""),
        ("app/regles/moteur.py", "or regle.version > dernieres[regle.code].version:", "or regle.version < dernieres[regle.code].version:"),
        ("app/regles/moteur.py", "        if applicabilite != NON:", "        if True:"),
        ("app/regles/moteur.py", "key=lambda r: (r.regle.type != OBLIGATION, r.regle.ordre, r.regle.code),", "key=lambda r: (r.regle.ordre, r.regle.code),"),
        ("app/regles/models.py", "STATUTS_VISIBLES = (A_VALIDER, PUBLIEE)", "STATUTS_VISIBLES = (BROUILLON, A_VALIDER, PUBLIEE)"),
        ("app/conversation/obligations.py", "r.regle.type == OBLIGATION and r.applicabilite != INCERTAIN]", "r.regle.type == OBLIGATION]"),
        ("app/conversation/obligations.py", "    if any(r.regle.statut == A_VALIDER for r in resultats):", "    if True:"),
        ("app/conversation/obligations.py", "echeance=regle.echeance or mf.A_CONFIRMER", "echeance=regle.echeance"),
        ("app/conversation/obligations.py", "    if parties:\n        return \", \".join(parties)", "    if True:\n        return \", \".join(parties)"),
        ("app/conversation/obligations.py", "    return regle.source_url or mf.SOURCE_A_COMPLETER", "    return mf.SOURCE_A_COMPLETER"),
        ("app/conversation/obligations.py", "aujourd_hui(juridiction.fuseau_horaire)", 'aujourd_hui("UTC")'),
        ("app/conversation/moteur.py", "    if not sans_profil and mots == CHOIX_OBLIGATIONS:", "    if False:"),
        ("app/core/temps.py", "datetime.now(ZoneInfo(fuseau_horaire)).date()", "datetime.now().date()"),
        ("migrations/versions/0004_regles.py", 'sa.UniqueConstraint("juridiction_code", "code", "version", name="uq_regles_juridiction_code_version"),', ""),
    ],
    "lot05": [
        ("app/calendrier/dates.py", 'premier = "1er" if jour.day == 1 else str(jour.day)', "premier = str(jour.day)"),
        ("app/calendrier/dates.py", "JOURS[jour.weekday()]} {premier}", "JOURS[jour.weekday() - 1]} {premier}"),
        ("app/calendrier/dates.py", "    if jours == 0:\n        return \"aujourd'hui\"", "    if False:\n        return \"aujourd'hui\""),
        ("app/calendrier/dates.py", "    if jours == 1:\n        return \"demain\"", "    if False:\n        return \"demain\""),
        ("app/calendrier/dates.py", "        if aujourd_hui.day > jour:", "        if aujourd_hui.day >= jour:"),
        ("app/calendrier/dates.py", "        annee_periode, mois_periode = mois_precedent(annee, mois)", "        annee_periode, mois_periode = annee, mois"),
        ("app/calendrier/dates.py", "    return (annee + 1, 1) if mois == 12 else (annee, mois + 1)", "    return (annee, 1) if mois == 12 else (annee, mois + 1)"),
        ("app/calendrier/dates.py", "    return (annee - 1, 12) if mois == 1 else (annee, mois - 1)", "    return (annee, 12) if mois == 1 else (annee, mois - 1)"),
        ("app/calendrier/dates.py", "if mois in (1, 4, 7, 10) and date(annee, mois, jour) >= aujourd_hui:", "if mois in (1, 4, 7, 10) and date(annee, mois, jour) > aujourd_hui:"),
        ("app/calendrier/dates.py", "                trimestre = (mois - 1) // 3 or 4", "                trimestre = (mois - 1) // 3 + 1"),
        ("app/calendrier/dates.py", "                annee_periode = annee - 1 if mois == 1 else annee", "                annee_periode = annee"),
        ("app/calendrier/dates.py", '                ordinal = "1er" if trimestre == 1 else f"{trimestre}e"', '                ordinal = f"{trimestre}e"'),
        ("app/calendrier/dates.py", "    if candidate < aujourd_hui:", "    if candidate <= aujourd_hui:"),
        ("app/calendrier/dates.py", "    if PERIODICITE_ATTENDUE[calcul[\"type\"]] != periodicite:", "    if False:"),
        ("app/calendrier/dates.py", "            if not isinstance(valeur, int) or isinstance(valeur, bool) or not 1 <= valeur <= maximum:", "            if not isinstance(valeur, int) or not 1 <= valeur <= maximum:"),
        ("app/calendrier/dates.py", "JOUR_MAX = 28", "JOUR_MAX = 31"),
        ("app/calendrier/dates.py", '    attendus = {"type", "jour"} | ({"mois"} if calcul["type"] == ANNUEL else set())', '    attendus = {"type", "jour", "mois"} if calcul["type"] == ANNUEL else set(calcul)'),
        ("app/calendrier/feries.py", '    (5, 20): "Fête nationale",', ""),
        ("app/calendrier/feries.py", '    (2, 11): "Fête de la Jeunesse",', ""),
        ("app/calendrier/feries.py", "    if jour == dimanche_paques - timedelta(days=2):", "    if jour == dimanche_paques - timedelta(days=1):"),
        ("app/calendrier/feries.py", "    if jour == dimanche_paques + timedelta(days=39):", "    if jour == dimanche_paques + timedelta(days=40):"),
        ("app/calendrier/feries.py", "    h = (19 * a + b - d - g + 15) % 30", "    h = (19 * a + b - d - g + 16) % 30"),
        ("app/calendrier/feries.py", "    return feries_mobiles().get(jour)", "    return None"),
        ("app/conversation/echeances.py", "    if jour.weekday() >= 5:", "    if jour.weekday() >= 6:"),
        ("app/conversation/echeances.py", "    nom = jour_ferie(jour)\n    if nom:", "    nom = jour_ferie(jour)\n    if False:"),
        ("app/conversation/echeances.py", "        key=lambda element: element[0],", "        key=lambda element: element[1],"),
        ("app/conversation/echeances.py", "    certaines = [r.regle for r in resultats if r.applicabilite != INCERTAIN]", "    certaines = [r.regle for r in resultats]"),
        ("app/conversation/echeances.py", "if r.regle.type == OBLIGATION]", "]"),
        ("app/conversation/echeances.py", "    if any(r.regle.statut == A_VALIDER for r in resultats):", "    if True:"),
        ("app/conversation/echeances.py", "    if regle.periodicite == PONCTUELLE:\n        return f\"• {regle.titre}\"", "    if False:\n        return f\"• {regle.titre}\""),
        ("app/conversation/echeances.py", "    ce_jour = aujourd_hui(juridiction.fuseau_horaire)", '    ce_jour = aujourd_hui("UTC")'),
        ("app/conversation/moteur.py", "    if not sans_profil and mots == CHOIX_ECHEANCES:", "    if False:"),
        ("app/regles/chargement.py", '    if brute.get("echeance_calcul") is not None:', "    if False:"),
    ],
    "lot06": [
        ("app/conversation/messages_fixes.py", '    ("5", "Mon entreprise"),\n', ""),
        ("app/conversation/moteur.py", 'CHOIX_AVEC_PROFIL = {"1", "2", "3", "5"}', 'CHOIX_AVEC_PROFIL = {"1", "2", "3"}'),
        ("app/conversation/moteur.py", "    if not sans_profil and mots == CHOIX_PROFIL:", "    if False:"),
        ("app/conversation/moteur.py", "    if not sans_profil and mots in MODIFIER and parcours is None:", "    if mots in MODIFIER and parcours is None:"),
        ("app/conversation/moteur.py", "        reprise_modification = parcours.type == profil.TYPE and mots in MODIFIER", "        reprise_modification = False"),
        ("app/conversation/moteur.py", "            annule = mf.MODIFICATION_ANNULEE if parcours.type == profil.TYPE else mf.ANNULE", "            annule = mf.ANNULE"),
        ("app/conversation/moteur.py", "        if parcours.type == profil.TYPE:\n            return profil.avancer", "        if False:\n            return profil.avancer"),
        ("app/conversation/onboarding.py", '            ligne += f" ({mf.NON_MODIFIABLE})"', "            pass"),
        ("app/conversation/onboarding.py", "    if type_parcours == MODIFICATION:\n        lignes", "    if False:\n        lignes"),
        ("app/conversation/onboarding.py", '        return [e for e in visibles if e.cle != "niu"]', "        return visibles"),
        ("app/conversation/onboarding.py", "    texte = mf.MODIFICATION_QUELLE if parcours.type == MODIFICATION else mf.CORRECTION", "    texte = mf.CORRECTION"),
        ("app/conversation/onboarding.py", '    "raison_sociale", "forme_juridique", "secteur",', '    "forme_juridique", "secteur",'),
        ("app/conversation/profil.py", '        "assujetti_tva_declare": INCONNU if tva is None else ("oui" if tva else "non"),', '        "assujetti_tva_declare": "oui" if tva else "non",'),
        ("app/conversation/profil.py", "    if onboarding.PAR_CLE[CNPS].condition(donnees):\n        donnees[CNPS]", "    if True:\n        donnees[CNPS]"),
        ("app/conversation/profil.py", "        mf.PROFIL_NIU,\n", ""),
        ("app/conversation/profil.py", "        if mots in OUI:\n            return finaliser(session", "        if mots in CORRIGER:\n            return finaliser(session"),
        ("app/conversation/profil.py", "        return Reponse(mf.ERR_CHOIX, list(mf.CHOIX_RECAP_MODIFICATION))", "        return Reponse(mf.ERR_CHOIX, list(mf.CHOIX_RECAP))"),
        ("app/conversation/profil.py", "    if CNPS in donnees:\n        valeurs[CNPS] = donnees[CNPS]", "    valeurs[CNPS] = donnees.get(CNPS)"),
        ("app/conversation/profil.py", "        if champ in avant and avant[champ] == nouvelle:\n            continue", "        if False:\n            continue"),
        ("app/conversation/profil.py", "        if ancienne == nouvelle:\n            continue", "        if False:\n            continue"),
        ("app/conversation/profil.py", "            conversation_id=conversation.id,\n            champ", "            champ"),
        ("app/conversation/profil.py", "            ancienne_valeur=ancienne,", "            ancienne_valeur=nouvelle,"),
        ("app/conversation/profil.py", "        setattr(entreprise, champ, nouvelle)\n", ""),
        ("app/conversation/profil.py", "    if changements == 0:", "    if changements < 0:"),
        ("app/conversation/profil.py", "    parcours.statut = TERMINE\n    avant", "    avant"),
        ("app/entreprises/models.py", "    ancienne_valeur: Mapped[object | None] = mapped_column(JSONB(none_as_null=True), default=None)", "    ancienne_valeur: Mapped[object | None] = mapped_column(JSONB(), default=None)"),
        ("app/entreprises/models.py", "    nouvelle_valeur: Mapped[object | None] = mapped_column(JSONB(none_as_null=True), default=None)", "    nouvelle_valeur: Mapped[object | None] = mapped_column(JSONB(), default=None)"),
    ],
    "lot07": [
        ("app/rappels/preparation.py", "PALIERS = (7, 2)", "PALIERS = (7, 3)"),
        ("app/rappels/preparation.py", "    return jour.weekday() < 5 and jour_ferie(jour) is None", "    return jour.weekday() < 6 and jour_ferie(jour) is None"),
        ("app/rappels/preparation.py", "    return jour.weekday() < 5 and jour_ferie(jour) is None", "    return jour.weekday() < 5"),
        ("app/rappels/preparation.py", "    if not jour_ouvre(date_limite):\n        dernier_ouvre", "    if False:\n        dernier_ouvre"),
        ("app/rappels/preparation.py", "        while not jour_ouvre(dernier_ouvre):", "        if not jour_ouvre(dernier_ouvre):"),
        ("app/rappels/preparation.py", "        prevue = min(prevue, dernier_ouvre)", "        prevue = dernier_ouvre"),
        ("app/rappels/preparation.py", "        if regle.type != OBLIGATION or resultat.applicabilite", "        if resultat.applicabilite"),
        ("app/rappels/preparation.py", " or resultat.applicabilite == INCERTAIN or not regle.echeance_calcul:", " or not regle.echeance_calcul:"),
        ("app/rappels/preparation.py", "        dus = [p for p in PALIERS if date_prevue(echeance.date_limite, p) <= ce_jour]", "        dus = [p for p in PALIERS if date_prevue(echeance.date_limite, p) < ce_jour]"),
        ("app/rappels/preparation.py", "        palier = min(dus)", "        palier = max(dus)"),
        ("app/rappels/preparation.py", "        if any(r.palier <= palier for r in existants):", "        if any(r.palier == palier for r in existants):"),
        ("app/rappels/preparation.py", "            if ancien.statut == A_ENVOYER:\n                ancien.statut = IGNORE", "            if True:\n                ancien.statut = IGNORE"),
        ("app/rappels/preparation.py", "            Rappel.date_limite == echeance.date_limite,\n        )))", "        )))"),
        ("app/rappels/preparation.py", "            regle_id=regle.id,", "            regle_id=regles_inconnue,"),
        ("app/rappels/preparation.py", "    for juridiction in session.scalars(select(Juridiction).where(Juridiction.active.is_(True))):", "    for juridiction in session.scalars(select(Juridiction)):"),
        ("app/rappels/preparation.py", "        ce_jour = jour or aujourd_hui(juridiction.fuseau_horaire)", "        ce_jour = jour or aujourd_hui(\"UTC\")"),
        ("app/rappels/livraison.py", "    if alerte:\n        lignes.append(alerte)", "    if False:\n        lignes.append(alerte)"),
        ("app/rappels/livraison.py", "    if regle.statut == A_VALIDER:", "    if True:"),
        ("app/rappels/livraison.py", "        if rappel.date_limite < ce_jour:", "        if rappel.date_limite <= ce_jour:"),
        ("app/rappels/livraison.py", "        rappel.statut = ENVOYE\n", ""),
        ("app/rappels/livraison.py", "        rappel.conversation_id = conversation.id\n", ""),
        ("app/rappels/livraison.py", "        rappel.envoye_le = datetime.now(timezone.utc)\n", ""),
        ("app/rappels/livraison.py", "        .order_by(Rappel.date_limite, Rappel.id)", "        .order_by(Rappel.id.desc())"),
        ("app/rappels/livraison.py", "        .where(Rappel.entreprise_id == entreprise.id, Rappel.statut == A_ENVOYER, Rappel.canal == BULLE)", "        .where(Rappel.statut == A_ENVOYER, Rappel.canal == BULLE)"),
        ("app/conversation/moteur.py", "    reponse.rappels = rappels\n", ""),
        ("app/conversation/moteur.py", "    for rappel in rappels:\n        session.add(Message(conversation_id=conversation.id, sens=SORTANT, texte=rappel))\n", ""),
        ("app/canaux/web.py", '            "rappels": reponse.rappels,\n', ""),
        ("app/static/js/essai.js", "      (donnees.rappels || []).forEach(function (r) { ajouterBulle(r, \"sortant\", \"jeff-rappel\"); });\n", ""),
        ("app/worker.py", "crontab(hour=7, minute=30)", "crontab(hour=7, minute=0)"),
        ("app/worker.py", "        session.commit()\n        return nombre", "        return nombre"),
        ("app/worker.py", "    except Exception:\n        session.rollback()\n        raise", "    except Exception:\n        raise"),
        ("app/rappels/preparer.py", "        nombre = preparer_rappels(session, jour)\n        session.commit()", "        nombre = preparer_rappels(session, jour)"),
        ("app/rappels/preparer.py", "        jour = date.fromisoformat(arguments[0]) if arguments else None", "        jour = None"),
        ("app/core/config.py", 'VERSION = "0.7.0"', 'VERSION = "0.6.0"'),
        ("app/rappels/preparer.py", "from app import models as _modeles  # noqa: F401 (toutes les tables, pour les clés étrangères)\n", ""),
        ("app/worker.py", "    from app import models as _modeles  # noqa: F401 (toutes les tables connues)\n", ""),
    ],
}


def lancer_tests() -> bool:
    resultat = subprocess.run(
        [sys.executable, "-m", "pytest", "-x", "-q", "-p", "no:warnings"],
        cwd=RACINE,
        capture_output=True,
    )
    return resultat.returncode == 0


def main(lot: str) -> int:
    survivantes = []
    for fichier, avant, apres in MUTATIONS[lot]:
        chemin = RACINE / fichier
        original = chemin.read_text()
        if original.count(avant) != 1:
            print(f"MUTATION INVALIDE ({fichier}) : texte introuvable ou ambigu : {avant!r}")
            return 2
        chemin.write_text(original.replace(avant, apres))
        try:
            tue = not lancer_tests()
        finally:
            chemin.write_text(original)
        print(f"{'tuée     ' if tue else 'SURVIVANTE'} {fichier} : {avant[:60]!r}")
        if not tue:
            survivantes.append((fichier, avant))
    total = len(MUTATIONS[lot])
    print(f"\n{total - len(survivantes)}/{total} mutations tuées.")
    return 1 if survivantes else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "lot01"))
