"""Contrôle par mutations : casse volontairement chaque règle et vérifie qu'un test échoue.

Usage : python scripts/mutations.py lot01
Chaque lot ajoute sa liste de mutations ci-dessous. Une mutation qui laisse tous les tests
verts signale un test manquant : le lot n'est pas livré tant qu'elle « survit ».
"""
import pathlib
import subprocess
import sys

RACINE = pathlib.Path(__file__).resolve().parent.parent

MUTATIONS = {
    "lot01": [
        ("app/core/sante.py", 'return {"statut": OK if tout_va_bien else INDISPONIBLE', 'return {"statut": OK'),
        ("app/core/sante.py", "all(valeur == OK", "any(valeur == OK"),
        ("app/core/sante.py", "        return OK\n    except Exception:\n        return INDISPONIBLE\n\n\ndef verifier_redis", "        return OK\n    except Exception:\n        return OK\n\n\ndef verifier_redis"),
        ("app/core/sante.py", "        client.ping()\n        return OK\n    except Exception:\n        return INDISPONIBLE", "        client.ping()\n        return OK\n    except Exception:\n        return OK"),
        ("app/main.py", "code = 200 if etat", "code = 200 or etat"),
        ("app/core/config.py", 'return self.environnement != "production"', "return True"),
        ("app/entreprises/niu.py", "if not niu:", "if False:"),
        ("app/entreprises/niu.py", "if len(niu) > LONGUEUR_MAX:", "if len(niu) > LONGUEUR_MAX + 1:"),
        ("app/entreprises/niu.py", ".upper()", ""),
        ("app/entreprises/niu.py", r're.sub(r"[\s\-]", "", valeur)', r're.sub(r"[\s]", "", valeur)'),
        ("app/entreprises/niu.py", "if not niu.isalnum():", "if False:"),
        ("app/entreprises/niu.py", "if valeur is None:", "if False:"),
        ("migrations/versions/0001_socle.py", '"active": True', '"active": False'),
        ("migrations/versions/0001_socle.py", 'sa.UniqueConstraint("juridiction_code", "niu", name="uq_entreprises_juridiction_niu"),', ""),
        ("migrations/versions/0001_socle.py", 'sa.UniqueConstraint("juridiction_code", "niu"', 'sa.UniqueConstraint("niu"'),
        ("migrations/versions/0001_socle.py", 'sa.ForeignKey("juridictions.code"), nullable=False', "nullable=False"),
    ],
    "lot02": [
        ("app/conversation/moteur.py", "return len(texte) > LONGUEUR_MAX", "return len(texte) > LONGUEUR_MAX + 1"),
        ("app/conversation/moteur.py", "if premier_mot in SALUTATIONS:", "if mots in SALUTATIONS:"),
        ("app/conversation/moteur.py", "if mots == valeur:", "if valeur in mots:"),
        ("app/conversation/normalisation.py", 'encode("ascii", "ignore")', 'encode("utf-8", "ignore")'),
        ("app/conversation/normalisation.py", ".lower()", ""),
        ("app/conversation/moteur.py", "if texte is None or not texte.strip():", "if texte is None:"),
        ("app/conversation/moteur.py", "texte=texte[:LONGUEUR_MAX]", "texte=texte"),
        ("app/conversation/moteur.py", "            Conversation.canal == canal, Conversation.identifiant_externe == identifiant\n        )", "            Conversation.identifiant_externe == identifiant\n        )"),
        ("app/conversation/moteur.py", ".where(Conversation.canal == canal, Conversation.identifiant_externe == identifiant)\n            .order_by", ".where(Conversation.canal == canal)\n            .order_by"),
        ("app/conversation/moteur.py", ".order_by(Message.id)", ".order_by(Message.id.desc())"),
        ("app/conversation/moteur.py", "return Reponse(mf.ACCUEIL, list(mf.MENU))", "return Reponse(mf.ACCUEIL)"),
        ("app/conversation/messages_fixes.py", "Tapez « menu » pour voir ce que je peux faire pour vous.", "Tape « menu » pour voir ce que je peux faire pour toi."),
        ("app/canaux/web.py", "if not get_settings().essai_actif:", "if False:"),
        ("app/canaux/web.py", "jeton = jeton_valide(request) or secrets.token_urlsafe(32)", "jeton = secrets.token_urlsafe(32)"),
        ("app/canaux/web.py", "if jeton and 20 <= len(jeton)", "if jeton and 0 <= len(jeton)"),
        ("app/canaux/web.py", 'jeton.replace("-", "").replace("_", "").isalnum()', "True"),
        ("app/canaux/web.py", "httponly=True", "httponly=False"),
        ("app/canaux/web.py", 'samesite="strict"', 'samesite="lax"'),
        ("app/canaux/web.py", "    if jeton is None:\n        raise HTTPException(status_code=401", "    if False:\n        raise HTTPException(status_code=401"),
        ("app/canaux/web.py", "raise HTTPException(status_code=422", "raise HTTPException(status_code=400"),
        ("app/static/js/essai.js", "bulle.textContent = texte;", "bulle.innerHTML = texte;"),
        ("docker-compose.yml", "${JEFF_PORT:-8020}", "${JEFF_PORT:-8010}"),
        # Mutation de l'import de app.models retirée au lot 4 : tous les modèles sont désormais
        # chargés par le chemin normal (app.main → canaux → conversation → regles), elle était équivalente.
        ("migrations/versions/0002_conversations.py", 'sa.UniqueConstraint("canal", "identifiant_externe", name="uq_conversations_canal_identifiant"),', ""),
    ],
    "lot03": [
        ("app/conversation/montants.py", 'brut = re.sub(UNITES_MONETAIRES, " ", brut)', "brut = brut"),
        ("app/conversation/montants.py", 'brut = re.sub(r"\\bde\\b", " ", brut).strip()', "brut = brut.strip()"),
        ("app/conversation/montants.py", "if unite not in MULTIPLICATEURS:", "if False:"),
        ("app/conversation/montants.py", "if valeur != valeur.to_integral_value():", "if False:"),
        ("app/conversation/montants.py", 'chiffres.replace(",", ".")', "chiffres"),
        ("app/conversation/montants.py", r're.fullmatch(r"\d{1,3}(\.\d{3})+", chiffres)', r're.fullmatch(r"[\d.]+", chiffres)'),
        ("app/conversation/montants.py", "if montant > MONTANT_MAX:", "if montant > MONTANT_MAX * 10:"),
        ("app/conversation/montants.py", '"million": 10**6, "millions": 10**6, "m": 10**6', '"million": 10**6, "millions": 10**3, "m": 10**6'),
        ("app/conversation/montants.py", "if normaliser(texte) in MOTS_ZERO:", "if False:"),
        ("app/conversation/montants.py", "chiffres = re.sub(ESPACES, \"\", texte)", "chiffres = re.sub(ESPACES, \"\", normaliser(texte))"),
        ("app/conversation/montants.py", "if nombre > maximum:", "if nombre > maximum + 1:"),
        ("app/conversation/montants.py", 'return f"{montant:,}".replace(",", ESPACE_INSECABLE)', 'return f"{montant:,}".replace(",", " ")'),
        ("app/conversation/onboarding.py", "if len(valeur) < minimum:", "if len(valeur) < minimum - 1:"),
        ("app/conversation/onboarding.py", "if len(valeur) > maximum:", "if len(valeur) > maximum + 1:"),
        ("app/conversation/onboarding.py", "    if niu_deja_connu(session, niu):\n        raise ReponseInvalide(mf.NIU_DEJA_CONNU)", "    if False:\n        raise ReponseInvalide(mf.NIU_DEJA_CONNU)"),
        ("app/conversation/onboarding.py", "Entreprise.juridiction_code == get_settings().juridiction, Entreprise.niu == niu", "Entreprise.niu == niu"),
        ("app/conversation/onboarding.py", "if mots in {str(numero), normaliser(libelle), *synonymes}:", "if mots in {str(numero), *synonymes}:"),
        ("app/conversation/onboarding.py", "if not numero.isalnum() or not 3 <= len(numero) <= 30:", "if not 3 <= len(numero) <= 30:"),
        ("app/conversation/onboarding.py", 'if mots in {"plus tard", "je ne sais pas", "je ne l ai pas", "inconnu"}:', "if False:"),
        ("app/conversation/onboarding.py", 'condition=lambda donnees: (donnees.get("nombre_salaries") or 0) > 0,', "condition=lambda donnees: True,"),
        ("app/conversation/onboarding.py", "        if cle == \"nombre_salaries\" and cnps.condition(donnees) and cnps.cle not in donnees:", "        if False:"),
        ("app/conversation/onboarding.py", "    if donnees.get(RETOUR_RECAP):", "    if False:"),
        ("app/conversation/onboarding.py", '        donnees.pop("numero_employeur_cnps", None)', "        pass"),
        ("app/conversation/onboarding.py", "            parcours.statut = ABANDONNE\n            return Reponse(mf.PLUS_TARD", "            return Reponse(mf.PLUS_TARD"),
        ("app/conversation/onboarding.py", "if mots.isdigit() and 1 <= int(mots) <= len(proposees):", "if mots.isdigit() and 0 <= int(mots) <= len(proposees):"),
        ("app/conversation/onboarding.py", "    if niu_deja_connu(session, donnees[\"niu\"]):", "    if False:"),
        ("app/conversation/onboarding.py", '    valeurs["assujetti_tva_declare"] = None if tva == INCONNU else tva == "oui"', '    valeurs["assujetti_tva_declare"] = tva == "oui"'),
        ("app/conversation/onboarding.py", "    conversation.entreprise_id = entreprise.id\n", ""),
        ("app/conversation/onboarding.py", "    parcours.statut = TERMINE\n", ""),
        ("app/conversation/onboarding.py", "juridiction_code=get_settings().juridiction,", 'juridiction_code="CI",'),
        ("app/conversation/moteur.py", "            parcours.statut = EN_PAUSE\n", ""),
        ("app/conversation/moteur.py", "            parcours.statut = ABANDONNE\n            annule =", "            annule ="),
        ("app/conversation/moteur.py", "\n            or (sans_profil and mots in CHOIX_AVEC_PROFIL)", ""),
        ("app/conversation/moteur.py", "if sans_profil and mots in CHOIX_AVEC_PROFIL and parcours is None:", "if mots in CHOIX_AVEC_PROFIL and parcours is None:"),
        ("app/conversation/moteur.py", 'CHOIX_AVEC_PROFIL = {"1", "2", "3", "5"}', 'CHOIX_AVEC_PROFIL = {"1", "2", "3", "4", "5"}'),
        ("app/conversation/models.py", "postgresql_where=text(\"statut IN ('en_cours', 'en_pause')\"),", "postgresql_where=text(\"statut IN ('en_cours')\"),"),
        ("migrations/versions/0003_onboarding.py", "postgresql_where=sa.text(\"statut IN ('en_cours', 'en_pause')\"),", "postgresql_where=sa.text(\"statut IN ('en_cours')\"),"),
        ("migrations/versions/0003_onboarding.py", "        unique=True,\n", ""),
    ],
    "lot04": [
        ("app/regles/conditions.py", "        if NON in resultats:\n            return NON\n        return INCERTAIN if INCERTAIN in resultats else OUI", "        if NON in resultats:\n            return NON\n        return OUI"),
        ("app/regles/conditions.py", "        if NON in resultats:\n            return NON\n", "        if False:\n            return NON\n"),
        ("app/regles/conditions.py", "        if OUI in resultats:\n            return OUI\n", "        if False:\n            return OUI\n"),
        ("app/regles/conditions.py", "        return INCERTAIN if INCERTAIN in resultats else NON", "        return NON"),
        ("app/regles/conditions.py", "return {OUI: NON, NON: OUI}.get(resultat, INCERTAIN)", "return {OUI: NON, NON: OUI}.get(resultat, NON)"),
        ("app/regles/conditions.py", "    if valeur is None:\n        return INCERTAIN", "    if valeur is None:\n        return NON"),
        ("app/regles/conditions.py", "        return OUI if valeur is None else NON", "        return OUI"),
        ("app/regles/conditions.py", "        return NON if valeur is None else OUI", "        return OUI"),
        ("app/regles/conditions.py", '"superieur": lambda a, b: a > b,', '"superieur": lambda a, b: a >= b,'),
        ("app/regles/conditions.py", '"inferieur": lambda a, b: a < b,', '"inferieur": lambda a, b: a <= b,'),
        ("app/regles/conditions.py", '"superieur_ou_egal": lambda a, b: a >= b,', '"superieur_ou_egal": lambda a, b: a > b,'),
        ("app/regles/conditions.py", '"inferieur_ou_egal": lambda a, b: a <= b,', '"inferieur_ou_egal": lambda a, b: a < b,'),
        ("app/regles/conditions.py", '"different": lambda a, b: a != b,', '"different": lambda a, b: a == b,'),
        ("app/regles/conditions.py", "    if champ not in CHAMPS:", "    if False:"),
        ("app/regles/conditions.py", "    if op not in COMPARAISONS:", "    if False:"),
        ("app/regles/conditions.py", '    if op == "dans" and not isinstance(condition["valeur"], list):', "    if False:"),
        ("app/regles/conditions.py", '        if condition != {"toujours": True}:', "        if False:"),
        ("app/regles/conditions.py", "        if len(condition) != 1 or not isinstance(sous, list) or not sous:", "        if not isinstance(sous, list):"),
        ("app/regles/conditions.py", '    if set(condition) != {"champ", "op", "valeur"}:', "    if False:"),
        ("app/regles/conditions.py", "    except TypeError:", "    except KeyError:"),
        ("app/regles/chargement.py", '    if not isinstance(brute["code"], str) or not re.fullmatch(r"[A-Z0-9_]{3,60}", brute["code"]):', '    if not isinstance(brute["code"], str):'),
        ("app/regles/chargement.py", 'or isinstance(brute["version"], bool) or brute["version"] < 1:', 'or brute["version"] < 1:'),
        ("app/regles/chargement.py", '    if brute["type"] == "obligation" and periodicite is None:', "    if False:"),
        ("app/regles/chargement.py", "    if du and au and au < du:", "    if False:"),
        ("app/regles/chargement.py", "            if cle in vues:", "            if False:"),
        ("app/regles/chargement.py", "        if deja is not None and contenu(deja) != contenu(regle):", "        if False:"),
        ("app/regles/chargement.py", "    if erreurs:\n        raise ReglesInvalides(erreurs)\n\n    bilan", "    if False:\n        raise ReglesInvalides(erreurs)\n\n    bilan"),
        ("app/regles/chargement.py", "        elif deja.statut != regle[\"statut\"]:\n            deja.statut = regle[\"statut\"]", "        elif deja.statut != regle[\"statut\"]:\n            pass"),
        ("app/regles/chargement.py", 'CONTENU = (REQUIS | OPTIONNELS) - {"statut"}', "CONTENU = REQUIS | OPTIONNELS"),
        ("app/regles/chargement.py", "    if session.get(Juridiction, juridiction) is None:", "    if False:"),
        ("app/regles/charger.py", "        return 1", "        return 0"),
        ("app/regles/moteur.py", '"regime_declare": None if regime == INCONNU else regime,', '"regime_declare": regime,'),
        ("app/regles/moteur.py", "            Regle.statut.in_(STATUTS_VISIBLES),\n", ""),
        ("app/regles/moteur.py", "            Regle.applicable_du <= jour,\n", ""),
        ("app/regles/moteur.py", "or_(Regle.applicable_au.is_(None), Regle.applicable_au >= jour),", "or_(Regle.applicable_au.is_(None), Regle.applicable_au > jour),"),
        ("app/regles/moteur.py", "            Regle.juridiction_code == juridiction,\n", ""),
        ("app/regles/moteur.py", "or regle.version > dernieres[regle.code].version:", "or regle.version < dernieres[regle.code].version:"),
        ("app/regles/moteur.py", "        if applicabilite != NON:", "        if True:"),
        ("app/regles/moteur.py", "key=lambda r: (r.regle.type != OBLIGATION, r.regle.ordre, r.regle.code),", "key=lambda r: (r.regle.ordre, r.regle.code),"),
        ("app/regles/models.py", "STATUTS_VISIBLES = (A_VALIDER, PUBLIEE)", "STATUTS_VISIBLES = (BROUILLON, A_VALIDER, PUBLIEE)"),
        ("app/conversation/obligations.py", "r.regle.type == OBLIGATION and r.applicabilite != INCERTAIN]", "r.regle.type == OBLIGATION]"),
        ("app/conversation/obligations.py", "    if any(r.regle.statut == A_VALIDER for r in resultats):", "    if True:"),
        ("app/conversation/obligations.py", "echeance=regle.echeance or mf.A_CONFIRMER", "echeance=regle.echeance"),
        ("app/conversation/obligations.py", "    if parties:\n        return \", \".join(parties)", "    if True:\n        return \", \".join(parties)"),
        ("app/conversation/obligations.py", "    return regle.source_url or mf.SOURCE_A_COMPLETER", "    return mf.SOURCE_A_COMPLETER"),
        ("app/conversation/obligations.py", "aujourd_hui(juridiction.fuseau_horaire)", 'aujourd_hui("UTC")'),
        ("app/conversation/moteur.py", "    if not sans_profil and mots == CHOIX_OBLIGATIONS:", "    if False:"),
        ("app/core/temps.py", "datetime.now(ZoneInfo(fuseau_horaire)).date()", "datetime.now().date()"),
        ("migrations/versions/0004_regles.py", 'sa.UniqueConstraint("juridiction_code", "code", "version", name="uq_regles_juridiction_code_version"),', ""),
    ],
    "lot05": [
        ("app/calendrier/dates.py", 'premier = "1er" if jour.day == 1 else str(jour.day)', "premier = str(jour.day)"),
        ("app/calendrier/dates.py", "JOURS[jour.weekday()]} {premier}", "JOURS[jour.weekday() - 1]} {premier}"),
        ("app/calendrier/dates.py", "    if jours == 0:\n        return \"aujourd'hui\"", "    if False:\n        return \"aujourd'hui\""),
        ("app/calendrier/dates.py", "    if jours == 1:\n        return \"demain\"", "    if False:\n        return \"demain\""),
        ("app/calendrier/dates.py", "        if aujourd_hui.day > jour:", "        if aujourd_hui.day >= jour:"),
        ("app/calendrier/dates.py", "        annee_periode, mois_periode = mois_precedent(annee, mois)", "        annee_periode, mois_periode = annee, mois"),
        ("app/calendrier/dates.py", "    return (annee + 1, 1) if mois == 12 else (annee, mois + 1)", "    return (annee, 1) if mois == 12 else (annee, mois + 1)"),
        ("app/calendrier/dates.py", "    return (annee - 1, 12) if mois == 1 else (annee, mois - 1)", "    return (annee, 12) if mois == 1 else (annee, mois - 1)"),
        ("app/calendrier/dates.py", "if mois in (1, 4, 7, 10) and date(annee, mois, jour) >= aujourd_hui:", "if mois in (1, 4, 7, 10) and date(annee, mois, jour) > aujourd_hui:"),
        ("app/calendrier/dates.py", "                trimestre = (mois - 1) // 3 or 4", "                trimestre = (mois - 1) // 3 + 1"),
        ("app/calendrier/dates.py", "                annee_periode = annee - 1 if mois == 1 else annee", "                annee_periode = annee"),
        ("app/calendrier/dates.py", '                ordinal = "1er" if trimestre == 1 else f"{trimestre}e"', '                ordinal = f"{trimestre}e"'),
        ("app/calendrier/dates.py", "    if candidate < aujourd_hui:", "    if candidate <= aujourd_hui:"),
        ("app/calendrier/dates.py", "    if PERIODICITE_ATTENDUE[calcul[\"type\"]] != periodicite:", "    if False:"),
        ("app/calendrier/dates.py", "            if not isinstance(valeur, int) or isinstance(valeur, bool) or not 1 <= valeur <= maximum:", "            if not isinstance(valeur, int) or not 1 <= valeur <= maximum:"),
        ("app/calendrier/dates.py", "JOUR_MAX = 28", "JOUR_MAX = 31"),
        ("app/calendrier/dates.py", '    attendus = {"type", "jour"} | ({"mois"} if calcul["type"] == ANNUEL else set())', '    attendus = {"type", "jour", "mois"} if calcul["type"] == ANNUEL else set(calcul)'),
        ("app/calendrier/feries.py", '    (5, 20): "Fête nationale",', ""),
        ("app/calendrier/feries.py", '    (2, 11): "Fête de la Jeunesse",', ""),
        ("app/calendrier/feries.py", "    if jour == dimanche_paques - timedelta(days=2):", "    if jour == dimanche_paques - timedelta(days=1):"),
        ("app/calendrier/feries.py", "    if jour == dimanche_paques + timedelta(days=39):", "    if jour == dimanche_paques + timedelta(days=40):"),
        ("app/calendrier/feries.py", "    h = (19 * a + b - d - g + 15) % 30", "    h = (19 * a + b - d - g + 16) % 30"),
        ("app/calendrier/feries.py", "    return feries_mobiles().get(jour)", "    return None"),
        ("app/conversation/echeances.py", "    if jour.weekday() >= 5:", "    if jour.weekday() >= 6:"),
        ("app/conversation/echeances.py", "    nom = jour_ferie(jour)\n    if nom:", "    nom = jour_ferie(jour)\n    if False:"),
        ("app/conversation/echeances.py", "        key=lambda element: element[0],", "        key=lambda element: element[1],"),
        ("app/conversation/echeances.py", "    certaines = [r.regle for r in resultats if r.applicabilite != INCERTAIN]", "    certaines = [r.regle for r in resultats]"),
        ("app/conversation/echeances.py", "if r.regle.type == OBLIGATION]", "]"),
        ("app/conversation/echeances.py", "    if any(r.regle.statut == A_VALIDER for r in resultats):", "    if True:"),
        ("app/conversation/echeances.py", "    if regle.periodicite == PONCTUELLE:\n        return f\"• {regle.titre}\"", "    if False:\n        return f\"• {regle.titre}\""),
        ("app/conversation/echeances.py", "    ce_jour = aujourd_hui(juridiction.fuseau_horaire)", '    ce_jour = aujourd_hui("UTC")'),
        ("app/conversation/moteur.py", "    if not sans_profil and mots == CHOIX_ECHEANCES:", "    if False:"),
        ("app/regles/chargement.py", '    if brute.get("echeance_calcul") is not None:', "    if False:"),
    ],
    "lot06": [
        ("app/conversation/messages_fixes.py", '    ("5", "Mon entreprise"),\n', ""),
        ("app/conversation/moteur.py", 'CHOIX_AVEC_PROFIL = {"1", "2", "3", "5"}', 'CHOIX_AVEC_PROFIL = {"1", "2", "3"}'),
        ("app/conversation/moteur.py", "    if not sans_profil and mots == CHOIX_PROFIL:", "    if False:"),
        ("app/conversation/moteur.py", "    if not sans_profil and mots in MODIFIER and parcours is None:", "    if mots in MODIFIER and parcours is None:"),
        ("app/conversation/moteur.py", "        reprise_modification = parcours.type == profil.TYPE and mots in MODIFIER", "        reprise_modification = False"),
        ("app/conversation/moteur.py", "            annule = ANNULATIONS.get(parcours.type, mf.ANNULE)", "            annule = mf.ANNULE"),
        ("app/conversation/moteur.py", "        if parcours.type == profil.TYPE:\n            return profil.avancer", "        if False:\n            return profil.avancer"),
        ("app/conversation/onboarding.py", '            ligne += f" ({mf.NON_MODIFIABLE})"', "            pass"),
        ("app/conversation/onboarding.py", "    if type_parcours == MODIFICATION:\n        lignes", "    if False:\n        lignes"),
        ("app/conversation/onboarding.py", '        return [e for e in visibles if e.cle != "niu"]', "        return visibles"),
        ("app/conversation/onboarding.py", "    texte = mf.MODIFICATION_QUELLE if parcours.type == MODIFICATION else mf.CORRECTION", "    texte = mf.CORRECTION"),
        ("app/conversation/onboarding.py", '    "raison_sociale", "forme_juridique", "secteur",', '    "forme_juridique", "secteur",'),
        ("app/conversation/profil.py", '        "assujetti_tva_declare": INCONNU if tva is None else ("oui" if tva else "non"),', '        "assujetti_tva_declare": "oui" if tva else "non",'),
        ("app/conversation/profil.py", "    if onboarding.PAR_CLE[CNPS].condition(donnees):\n        donnees[CNPS]", "    if True:\n        donnees[CNPS]"),
        ("app/conversation/profil.py", "        mf.PROFIL_NIU,\n", ""),
        ("app/conversation/profil.py", "        if mots in OUI:\n            return finaliser(session", "        if mots in CORRIGER:\n            return finaliser(session"),
        ("app/conversation/profil.py", "        return Reponse(mf.ERR_CHOIX, list(mf.CHOIX_RECAP_MODIFICATION))", "        return Reponse(mf.ERR_CHOIX, list(mf.CHOIX_RECAP))"),
        ("app/conversation/profil.py", "    if CNPS in donnees:\n        valeurs[CNPS] = donnees[CNPS]", "    valeurs[CNPS] = donnees.get(CNPS)"),
        ("app/conversation/profil.py", "        if champ in avant and avant[champ] == nouvelle:\n            continue", "        if False:\n            continue"),
        ("app/conversation/profil.py", "        if ancienne == nouvelle:\n            continue", "        if False:\n            continue"),
        ("app/conversation/profil.py", "            conversation_id=conversation.id,\n            champ", "            champ"),
        ("app/conversation/profil.py", "            ancienne_valeur=ancienne,", "            ancienne_valeur=nouvelle,"),
        ("app/conversation/profil.py", "        setattr(entreprise, champ, nouvelle)\n", ""),
        ("app/conversation/profil.py", "    if changements == 0:", "    if changements < 0:"),
        ("app/conversation/profil.py", "    parcours.statut = TERMINE\n    avant", "    avant"),
        ("app/entreprises/models.py", "    ancienne_valeur: Mapped[object | None] = mapped_column(JSONB(none_as_null=True), default=None)", "    ancienne_valeur: Mapped[object | None] = mapped_column(JSONB(), default=None)"),
        ("app/entreprises/models.py", "    nouvelle_valeur: Mapped[object | None] = mapped_column(JSONB(none_as_null=True), default=None)", "    nouvelle_valeur: Mapped[object | None] = mapped_column(JSONB(), default=None)"),
    ],
    "lot07": [
        ("app/rappels/preparation.py", "PALIERS = (7, 2)", "PALIERS = (7, 3)"),
        ("app/rappels/preparation.py", "    return jour.weekday() < 5 and jour_ferie(jour) is None", "    return jour.weekday() < 6 and jour_ferie(jour) is None"),
        ("app/rappels/preparation.py", "    return jour.weekday() < 5 and jour_ferie(jour) is None", "    return jour.weekday() < 5"),
        ("app/rappels/preparation.py", "    if not jour_ouvre(date_limite):\n        dernier_ouvre", "    if False:\n        dernier_ouvre"),
        ("app/rappels/preparation.py", "        while not jour_ouvre(dernier_ouvre):", "        if not jour_ouvre(dernier_ouvre):"),
        ("app/rappels/preparation.py", "        prevue = min(prevue, dernier_ouvre)", "        prevue = dernier_ouvre"),
        ("app/rappels/preparation.py", "        if regle.type != OBLIGATION or resultat.applicabilite", "        if resultat.applicabilite"),
        ("app/rappels/preparation.py", " or resultat.applicabilite == INCERTAIN or not regle.echeance_calcul:", " or not regle.echeance_calcul:"),
        ("app/rappels/preparation.py", "        dus = [p for p in PALIERS if date_prevue(echeance.date_limite, p) <= ce_jour]", "        dus = [p for p in PALIERS if date_prevue(echeance.date_limite, p) < ce_jour]"),
        ("app/rappels/preparation.py", "        palier = min(dus)", "        palier = max(dus)"),
        ("app/rappels/preparation.py", "        if any(r.palier <= palier for r in existants):", "        if any(r.palier == palier for r in existants):"),
        ("app/rappels/preparation.py", "            if ancien.statut == A_ENVOYER:\n                ancien.statut = IGNORE", "            if True:\n                ancien.statut = IGNORE"),
        ("app/rappels/preparation.py", "            Rappel.date_limite == echeance.date_limite,\n        )))", "        )))"),
        ("app/rappels/preparation.py", "            regle_id=regle.id,", "            regle_id=regles_inconnue,"),
        ("app/rappels/preparation.py", "    for juridiction in session.scalars(select(Juridiction).where(Juridiction.active.is_(True))):", "    for juridiction in session.scalars(select(Juridiction)):"),
        ("app/rappels/preparation.py", "        ce_jour = jour or aujourd_hui(juridiction.fuseau_horaire)", "        ce_jour = jour or aujourd_hui(\"UTC\")"),
        ("app/rappels/livraison.py", "    if alerte:\n        lignes.append(alerte)", "    if False:\n        lignes.append(alerte)"),
        ("app/rappels/livraison.py", "    if regle.statut == A_VALIDER:", "    if True:"),
        ("app/rappels/livraison.py", "        if rappel.date_limite < ce_jour:", "        if rappel.date_limite <= ce_jour:"),
        ("app/rappels/livraison.py", "        rappel.statut = ENVOYE\n", ""),
        ("app/rappels/livraison.py", "        rappel.conversation_id = conversation.id\n", ""),
        ("app/rappels/livraison.py", "        rappel.envoye_le = datetime.now(timezone.utc)\n", ""),
        ("app/rappels/livraison.py", "        .order_by(Rappel.date_limite, Rappel.id)", "        .order_by(Rappel.id.desc())"),
        ("app/rappels/livraison.py", "        .where(Rappel.entreprise_id == entreprise.id, Rappel.statut == A_ENVOYER, Rappel.canal == BULLE)", "        .where(Rappel.statut == A_ENVOYER, Rappel.canal == BULLE)"),
        ("app/conversation/moteur.py", "    reponse.rappels = rappels\n", ""),
        ("app/conversation/moteur.py", "    for rappel in rappels:\n        session.add(Message(conversation_id=conversation.id, sens=SORTANT, texte=rappel))\n", ""),
        ("app/canaux/web.py", '            "rappels": reponse.rappels,\n', ""),
        ("app/static/js/essai.js", "      (donnees.rappels || []).forEach(function (r) { ajouterBulle(r, \"sortant\", \"jeff-rappel\"); });\n", ""),
        ("app/worker.py", "crontab(hour=7, minute=30)", "crontab(hour=7, minute=0)"),
        ("app/worker.py", "        session.commit()\n        return nombre", "        return nombre"),
        ("app/worker.py", "        return nombre\n    except Exception:\n        session.rollback()\n        raise", "        return nombre\n    except Exception:\n        raise"),
        ("app/rappels/preparer.py", "        nombre = preparer_rappels(session, jour)\n        session.commit()", "        nombre = preparer_rappels(session, jour)"),
        ("app/rappels/preparer.py", "        jour = date.fromisoformat(arguments[0]) if arguments else None", "        jour = None"),
        ("app/rappels/preparer.py", "from app import models as _modeles  # noqa: F401 (toutes les tables, pour les clés étrangères)\n", ""),
        ("app/worker.py", "    from app import models as _modeles  # noqa: F401 (toutes les tables connues)\n    from app.core.db import get_session\n    from app.rappels", "    from app.core.db import get_session\n    from app.rappels"),
    ],
    "lot08": [
        ("app/conversation/onboarding.py", '    Etape("email", "Adresse email", mf.Q_EMAIL, lire_email, list(mf.CHOIX_EMAIL)),\n', ""),
        ("app/conversation/onboarding.py", "    if normaliser(texte) in SANS_EMAIL:\n        return None", "    if False:\n        return None"),
        ("app/conversation/onboarding.py", "    email = texte.strip().lower()", "    email = texte.strip()"),
        ("app/conversation/onboarding.py", "    if len(email) > EMAIL_MAX or not", "    if not"),
        ("app/conversation/onboarding.py", "\\.[a-z]{2,}\", email):", "\\.[a-z]{1,}\", email):"),
        ("app/conversation/onboarding.py", '    if ".." in email:\n        raise', '    if False:\n        raise'),
        ("app/conversation/onboarding.py", '    if cle in ("numero_employeur_cnps", "email") and valeur is None:', '    if cle == "numero_employeur_cnps" and valeur is None:'),
        ("app/conversation/onboarding.py", "    if entreprise.email:\n        session.flush()", "    if False:\n        session.flush()"),
        ("app/conversation/onboarding.py", '    valeurs["email"] = donnees.get("email")', '    valeurs["email"] = None'),
        ("app/conversation/confirmation.py", "DUREE = timedelta(minutes=15)", "DUREE = timedelta(minutes=30)"),
        ("app/conversation/confirmation.py", "ESSAIS_MAX = 5", "ESSAIS_MAX = 6"),
        ("app/conversation/confirmation.py", "RENVOIS_MAX = 3", "RENVOIS_MAX = 4"),
        ("app/conversation/confirmation.py", '    return hashlib.sha256(f"{parcours.id}:{code}".encode()).hexdigest()', '    return hashlib.sha256(code.encode()).hexdigest()'),
        ("app/conversation/confirmation.py", '        "essais": 0,\n    }', '    }'),
        ("app/conversation/confirmation.py", "    if entreprise.email != donnees[\"email\"]:", "    if False:"),
        ("app/conversation/confirmation.py", "        if donnees[\"renvois\"] >= RENVOIS_MAX:", "        if donnees[\"renvois\"] > RENVOIS_MAX:"),
        ("app/conversation/confirmation.py", '        parcours.donnees = {**donnees, "renvois": donnees["renvois"] + 1}\n', ""),
        ("app/conversation/confirmation.py", '    code = re.sub(r"[\\s.\\-]", "", texte)', "    code = texte"),
        ("app/conversation/confirmation.py", "    if maintenant() > datetime.fromisoformat(donnees[\"expire_le\"]):", "    if False:"),
        ("app/conversation/confirmation.py", "    if not hmac.compare_digest(empreinte(parcours, code), donnees[\"empreinte\"]):", "    if False:"),
        ("app/conversation/confirmation.py", "        if essais >= ESSAIS_MAX:", "        if essais > ESSAIS_MAX:"),
        ("app/conversation/confirmation.py", '        parcours.donnees = {**donnees, "essais": essais}\n', ""),
        ("app/conversation/confirmation.py", "    entreprise.email_confirme_le = maintenant()\n", ""),
        ("app/conversation/confirmation.py", "    parcours.statut = TERMINE\n", ""),
        ("app/conversation/profil.py", '    donnees["email"] = entreprise.email\n', ""),
        ("app/conversation/profil.py", "    return bool(entreprise.email) and entreprise.email_confirme_le is None", "    return entreprise.email_confirme_le is None"),
        ("app/conversation/profil.py", "        choix.insert(1, mf.CHOIX_CONFIRMER)", "        choix.append(mf.CHOIX_CONFIRMER)"),
        ("app/conversation/profil.py", "            entreprise.email_confirme_le = None\n", ""),
        ("app/conversation/profil.py", "    if email_a_confirmer(entreprise):\n        code = confirmation.demarrer", "    if False:\n        code = confirmation.demarrer"),
        ("app/conversation/moteur.py", "        reprise_confirmation = parcours.type == confirmation.TYPE and mots in CONFIRMER", "        reprise_confirmation = False"),
        ("app/conversation/moteur.py", "        if parcours.type == confirmation.TYPE:\n            return confirmation.avancer", "        if False:\n            return confirmation.avancer"),
        ("app/conversation/moteur.py", "        if profil.email_a_confirmer(entreprise):\n            return confirmation.demarrer", "        if True:\n            return confirmation.demarrer"),
        ("app/conversation/moteur.py", "    if parcours.type == confirmation.TYPE:\n        return confirmation.question(parcours)", "    if False:\n        return confirmation.question(parcours)"),
        ("app/conversation/moteur.py", "    confirmation.TYPE: mf.CONFIRMATION_ANNULEE,\n", ""),
        ("app/rappels/canal.py", "    if entreprise.email and entreprise.email_confirme_le is not None:", "    if entreprise.email:"),
        ("app/rappels/preparation.py", "        if rappel.canal == EMAIL:\n            session.flush()", "        if False:\n            session.flush()"),
        ("app/rappels/preparation.py", "                    .where(emails.Email.rappel_id == ancien.id, emails.Email.statut == emails.A_ENVOYER)", "                    .where(emails.Email.rappel_id == ancien.id)"),
        ("app/rappels/preparation.py", "                    .values(statut=emails.ANNULE)", "                    .values(statut=emails.A_ENVOYER)"),
        ("app/emails/composition.py", '        \'<p style="margin:0 0 12px">\' + escape(p).replace', '        \'<p style="margin:0 0 12px">\' + p.replace'),
        ("app/emails/composition.py", "        objet=objet[:OBJET_MAX],", "        objet=objet,"),
        ("app/emails/composition.py", "        mf.EMAIL_DESABONNEMENT,\n", ""),
        ("app/emails/envoi.py", "ESSAIS_MAX = 3", "ESSAIS_MAX = 4"),
        ("app/emails/envoi.py", "        smtp.starttls(context=ssl.create_default_context())\n", ""),
        ("app/emails/envoi.py", "    with smtplib.SMTP(reglages.smtp_hote, reglages.smtp_port, timeout=30) as smtp:", "    with smtplib.SMTP(reglages.smtp_hote, 587, timeout=30) as smtp:"),
        ("app/emails/envoi.py", '    message["Message-ID"] = make_msgid(domain=reglages.email_expediteur.split("@")[-1])\n', ""),
        ("app/emails/envoi.py", '    message.add_alternative(html, subtype="html")\n', ""),
        ("app/emails/envoi.py", '        email.erreur = f"{type(erreur).__name__}: {erreur}"[:500]', '        email.erreur = f"{type(erreur).__name__}: {erreur}"'),
        ("app/emails/envoi.py", "                rappel.canal = BULLE\n", ""),
        ("app/emails/envoi.py", "    if email.type == CODE:\n        email.texte", "    if False:\n        email.texte"),
        ("app/emails/envoi.py", "        rappel.statut = rappels.ENVOYE\n", ""),
        ("app/emails/envoi.py", "    email.erreur = None\n", ""),
        ("app/emails/envoi.py", "    if not get_settings().email_configure:\n        return Bilan(desactive=True)", "    if False:\n        return Bilan(desactive=True)"),
        ("app/emails/envoi.py", "        if email is None or email.statut != A_ENVOYER:", "        if email is None:"),
        ("app/core/config.py", '        return all(v and v != "A_REMPLACER" and "VOTRE_DOMAINE" not in v for v in valeurs)', '        return all(v and v != "A_REMPLACER" for v in valeurs)'),
        ("app/core/config.py", "        valeurs = (self.smtp_hote, self.smtp_utilisateur, self.smtp_mot_de_passe, self.email_expediteur)", "        valeurs = (self.smtp_hote, self.smtp_mot_de_passe, self.email_expediteur)"),
        ("app/emails/tester.py", "    if not reglages.email_configure:\n        print", "    if False:\n        print"),
        ("app/worker.py", '    "envoyer-emails": {"task": "jeff.envoyer_emails", "schedule": crontab()},\n', ""),
        ("app/worker.py", "    from app import models as _modeles  # noqa: F401 (toutes les tables connues)\n    from app.core.db import get_session\n    from app.emails", "    from app.core.db import get_session\n    from app.emails"),
        ("app/worker.py", "        bilan = envoyer_en_attente(session)\n        return {\"envoyes\": bilan.envoyes, \"echecs\": bilan.echecs, \"desactive\": bilan.desactive}\n    except Exception:\n        session.rollback()\n        raise\n    finally:\n        session.close()\n\n\n@celery_app.task(name=\"jeff.envoyer_whatsapp\")", "        bilan = envoyer_en_attente(session)\n        session.close()\n        return {\"envoyes\": bilan.envoyes, \"echecs\": bilan.echecs, \"desactive\": bilan.desactive}\n    except Exception:\n        session.rollback()\n        raise\n    finally:\n        session.close()\n\n\n@celery_app.task(name=\"jeff.envoyer_whatsapp\")"),
    ],
    "lot09": [
        ("app/conversation/messages_fixes.py", ', ("deja", "J\'ai déjà un profil"))', ")"),
        ("app/conversation/onboarding.py", "        if mots in liaison.DEJA:\n            parcours.statut = ABANDONNE", "        if False:\n            parcours.statut = ABANDONNE"),
        ("app/conversation/liaison.py", "            Entreprise.email_confirme_le.is_not(None),\n", ""),
        ("app/conversation/liaison.py", "            Entreprise.juridiction_code == get_settings().juridiction,\n", ""),
        ("app/conversation/liaison.py", "    if entreprise is not None:\n        code", "    if True:\n        code"),
        ("app/conversation/liaison.py", "        if email is None:\n            return Reponse(mf.ERR_EMAIL)", "        if False:\n            return Reponse(mf.ERR_EMAIL)"),
        ("app/conversation/liaison.py", "        if donnees[\"renvois\"] >= confirmation.RENVOIS_MAX:", "        if donnees[\"renvois\"] > confirmation.RENVOIS_MAX:"),
        ("app/conversation/liaison.py", "        parcours.donnees = {**donnees, \"renvois\": donnees[\"renvois\"] + 1}\n", ""),
        ("app/conversation/liaison.py", "    if confirmation.maintenant() > datetime.fromisoformat(donnees[\"expire_le\"]):", "    if False:"),
        ("app/conversation/liaison.py", "    if attendu is None or not hmac.compare_digest", "    if attendu is not None and not hmac.compare_digest"),
        ("app/conversation/liaison.py", "        if essais >= confirmation.ESSAIS_MAX:", "        if essais > confirmation.ESSAIS_MAX:"),
        ("app/conversation/liaison.py", "    if entreprise is None or entreprise.email != donnees[\"email\"] or entreprise.email_confirme_le is None:", "    if entreprise is None or entreprise.email != donnees[\"email\"]:"),
        ("app/conversation/liaison.py", " or entreprise.email != donnees[\"email\"] or", " or"),
        ("app/conversation/liaison.py", "    conversation.entreprise_id = entreprise.id\n", ""),
        ("app/conversation/liaison.py", '    code = re.sub(r"[\\s.\\-]", "", texte)', "    code = texte"),
        ("app/conversation/moteur.py", "    liaison.TYPE: mf.LIAISON_ANNULEE,\n", ""),
        ("app/conversation/moteur.py", "    if parcours.type == liaison.TYPE:\n        return liaison.question(parcours)", "    if False:\n        return liaison.question(parcours)"),
        ("app/conversation/moteur.py", "        if parcours.type == liaison.TYPE:\n            return liaison.avancer", "        if False:\n            return liaison.avancer"),
        ("app/conversation/moteur.py", "    conversation.dernier_message_client_le = datetime.now(timezone.utc)\n    rappels", "    rappels"),
        ("app/conversation/moteur.py", "FENETRE = timedelta(hours=24)", "FENETRE = timedelta(hours=25)"),
        ("app/conversation/moteur.py", "    if conversation.dernier_message_client_le is None:\n        return False", "    if conversation.dernier_message_client_le is None:\n        return True"),
        ("app/whatsapp/format.py", "BOUTONS_MAX = 3", "BOUTONS_MAX = 4"),
        ("app/whatsapp/format.py", "BOUTON_TITRE_MAX = 20", "BOUTON_TITRE_MAX = 24"),
        ("app/whatsapp/format.py", "LISTE_MAX = 10", "LISTE_MAX = 11"),
        ("app/whatsapp/format.py", "LIGNE_TITRE_MAX = 24", "LIGNE_TITRE_MAX = 25"),
        ("app/whatsapp/format.py", "CORPS_INTERACTIF_MAX = 1024", "CORPS_INTERACTIF_MAX = 1025"),
        ("app/whatsapp/format.py", "TEXTE_MAX = 4096", "TEXTE_MAX = 4097"),
        ("app/whatsapp/format.py", "        if len(libelle) > LIGNE_TITRE_MAX:\n            ligne", "        if False:\n            ligne"),
        ("app/whatsapp/format.py", "    for rappel in reponse.rappels:\n        messages += textes(rappel)\n", ""),
        ("app/whatsapp/format.py", "        corps = mf.WA_VOTRE_CHOIX\n", ""),
        ("app/whatsapp/format.py", "        if courant:\n            morceaux.append(courant)\n        while", "        while"),
        ("app/whatsapp/format.py", '    return "\\n".join(f"{v}. {l}" if v.isdigit() else', '    return "\\n".join(f"{v}. {l}" if True else'),
        ("app/whatsapp/format.py", '"preview_url": False', '"preview_url": True'),
        ("app/whatsapp/reception.py", "    if not entete or not entete.startswith(\"sha256=\") or not secret:", "    if not entete or not entete.startswith(\"sha256=\"):"),
        ("app/whatsapp/reception.py", "    return hmac.compare_digest(attendue, entete.removeprefix(\"sha256=\"))", "    return True"),
        ("app/whatsapp/reception.py", " or (valeur.get(\"metadata\") or {}).get(\"phone_number_id\") != numero:", ":"),
        ("app/whatsapp/reception.py", "            if changement.get(\"field\") != \"messages\" or", "            if"),
        ("app/whatsapp/reception.py", "    if not isinstance(donnees, dict) or donnees.get(\"object\") != \"whatsapp_business_account\":", "    if not isinstance(donnees, dict):"),
        ("app/whatsapp/reception.py", "        reponse = interactif.get(\"button_reply\") or interactif.get(\"list_reply\") or {}", "        reponse = interactif.get(\"button_reply\") or {}"),
        ("app/whatsapp/reception.py", "        if deja_recu(session, str(message[\"id\"])[:200], conversation.id):\n            continue", "        if False:\n            continue"),
        ("app/whatsapp/reception.py", "            conversation.dernier_message_client_le = datetime.now(timezone.utc)\n            reponse", "            reponse"),
        ("app/whatsapp/envoi.py", "ESSAIS_MAX = 3", "ESSAIS_MAX = 4"),
        ("app/whatsapp/envoi.py", "DELAI_REPRISE = timedelta(seconds=30)", "DELAI_REPRISE = timedelta(seconds=0)"),
        ("app/whatsapp/envoi.py", '.replace(get_settings().whatsapp_jeton or "\\0", "***")', ""),
        ("app/whatsapp/envoi.py", "    if envoi is None or envoi.statut != A_ENVOYER:", "    if envoi is None:"),
        ("app/whatsapp/envoi.py", "        if envoi.essais >= ESSAIS_MAX:\n            envoi.statut = ECHEC", "        if False:\n            envoi.statut = ECHEC"),
        ("app/whatsapp/envoi.py", "    envoi.erreur = None\n", ""),
        ("app/whatsapp/envoi.py", '        url_messages(), json=corps, headers={"Authorization": f"Bearer {reglages.whatsapp_jeton}"}, timeout=15', '        url_messages(), json=corps, headers={}, timeout=15'),
        ("app/whatsapp/envoi.py", '    if reponse.status_code >= 400:', '    if reponse.status_code > 400:'),
        ("app/whatsapp/envoi.py", "        .where(WhatsappEnvoi.statut == A_ENVOYER, WhatsappEnvoi.cree_le < limite)", "        .where(WhatsappEnvoi.cree_le < limite)"),
        ("app/whatsapp/envoi.py", "    if not get_settings().whatsapp_configure:\n        return Bilan(desactive=True)", "    if False:\n        return Bilan(desactive=True)"),
        ("app/canaux/whatsapp.py", "        reglages.whatsapp_configure\n        and ", "        "),
        ("app/canaux/whatsapp.py", '        and parametres.get("hub.mode") == "subscribe"\n', ""),
        ("app/canaux/whatsapp.py", "    if len(corps) > CORPS_MAX or not signature_valide", "    if not signature_valide"),
        ("app/canaux/whatsapp.py", "        for identifiant in identifiants:\n            envoyer_un(session, identifiant)\n", ""),
        ("app/canaux/whatsapp.py", "    if not get_settings().whatsapp_configure:\n        return JSONResponse", "    if False:\n        return JSONResponse"),
        ("app/main.py", "app.include_router(whatsapp.router)\n", ""),
        ("app/core/config.py", '        return all(v and v != "A_REMPLACER" for v in valeurs)\n\n    @property\n    def email_configure', '        return all(v for v in valeurs)\n\n    @property\n    def email_configure'),
        ("app/worker.py", '    "envoyer-whatsapp": {"task": "jeff.envoyer_whatsapp", "schedule": crontab()},\n', ""),
        ("app/worker.py", "    from app import models as _modeles  # noqa: F401 (toutes les tables connues)\n    from app.core.db import get_session\n    from app.whatsapp", "    from app.core.db import get_session\n    from app.whatsapp"),
        ("app/core/config.py", 'VERSION = "0.9.0"', 'VERSION = "0.8.0"'),
    ],
}


def lancer_tests() -> bool:
    resultat = subprocess.run(
        [sys.executable, "-m", "pytest", "-x", "-q", "-p", "no:warnings"],
        cwd=RACINE,
        capture_output=True,
    )
    return resultat.returncode == 0


def main(lot: str) -> int:
    survivantes = []
    for fichier, avant, apres in MUTATIONS[lot]:
        chemin = RACINE / fichier
        original = chemin.read_text()
        if original.count(avant) != 1:
            print(f"MUTATION INVALIDE ({fichier}) : texte introuvable ou ambigu : {avant!r}")
            return 2
        chemin.write_text(original.replace(avant, apres))
        try:
            tue = not lancer_tests()
        finally:
            chemin.write_text(original)
        print(f"{'tuée     ' if tue else 'SURVIVANTE'} {fichier} : {avant[:60]!r}")
        if not tue:
            survivantes.append((fichier, avant))
    total = len(MUTATIONS[lot])
    print(f"\n{total - len(survivantes)}/{total} mutations tuées.")
    return 1 if survivantes else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "lot01"))
